# Generated by Django 4.2.6 on 2023-10-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='finall_price',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=6),
            preserve_default=False,
        ),
    ]
