# Generated by Django 4.2.6 on 2023-10-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order_finall_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='finall_price',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
