# Generated by Django 4.2.6 on 2023-10-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_order_finall_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='featured_products',
        ),
        migrations.RemoveField(
            model_name='products',
            name='collection',
        ),
        migrations.AddField(
            model_name='products',
            name='collection',
            field=models.ManyToManyField(related_name='products', to='store.collection'),
        ),
    ]
