# Generated by Django 4.2.6 on 2023-10-29 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_collection_featured_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='collection',
        ),
        migrations.AddField(
            model_name='products',
            name='collection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='store.collection'),
            preserve_default=False,
        ),
    ]
