# Generated by Django 4.2.6 on 2023-10-29 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_products_collection_products_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='collection',
        ),
        migrations.AddField(
            model_name='products',
            name='collection',
            field=models.ManyToManyField(related_name='products', to='store.collection'),
        ),
    ]
