# Generated by Django 4.2.6 on 2023-10-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_image_collection_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_image',
            name='product',
        ),
        migrations.AddField(
            model_name='collection',
            name='image',
            field=models.ImageField(default=1, upload_to='store/collection'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(default=1, upload_to='store/product'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Collection_images',
        ),
        migrations.DeleteModel(
            name='product_image',
        ),
    ]
